version: '3.8'

services:

    backend:
        container_name: backend
        build:
            context: ../../.
            dockerfile: src/dockerfiles/Dockerfile
        ports:
            - 8000:8000
        # volumes:
        #     - "$PWD:/daVinci"
        # env_file:
        #     - .env
        networks:
            - net

networks:
    net:
