version: '3.8'

services:

    backend:
        container_name: backend
        build:
            context: ../../.
            dockerfile: src/dockerfiles/Dockerfile.develop
        ports:
            - 8000:8000
            - 8050:8050
        volumes:
            - "$PWD:/daVinci"
        env_file:
            - ../api/.env
        networks:
            - net

networks:
    net:
