version: '3.8'

services:

    backend:
        container_name: backend
        build:
            context: ../.
            dockerfile: dockerfiles/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - "$PWD/src:/daVinci"
        # env_file:
        #     - .env
        networks:
            - net

networks:
    net:
