@startuml Da Vinci
|Primer Contacto|
start


split
    :Redes Sociales;
split again
    :Recomendaciones de contactos;
split again
    :Páginas Web de terceros;
end split



:Landing page de Da Vinci;
note 
    * Visualiza:
    - El logotipo de Da Vinci
    - Una descripción de Da Vinci,
        destacando sus ventajas y beneficios
    - Un título que dice:
        "Prepárate para el éxito universitario"
    - Screenshots de la App
    - Una sección con testimonios
        de usuarios satisfechos
    - Los próximos examenes de admisión
    ====
    * Links para instalar en:
    - Android
    - iOS
end note



:Instalar App;
stop


|Da Vinci|
start
:Abre la App;
note
    Da Vinci:
    * Individual:
        - Una pregunta, envías tu respuesta y la califica
    * Grupo:
        - Un conjunto de preguntas (agrupadas por
        Área, Curso, Tema, etc), envía las
        respuestas de todo el grupo y las evalúa
    * Exámenes pasados:
        - Exámenes de admisión pasados, completos
end note
repeat :Home de Da Vinci;
    split 
        :Selecciona Grupo;
        note
            * Un conjunto de preguntas, agrupadas por:
            - Área
            - Curso
            - Tema
            ====
            * Envía las respuestas de todo el grupo y
                las evalúa en conjunto
        end note
    end


    split again
        :Exámenes pasados;
        note
            * Exámenes de admisión completos
            * Envía todas las respuestas y
                las evalúa en conjunto
        end note
    end


    split again
        :Pregunta Individual;
        note
            * Una pregunta,
                envías tu respuesta,
                la califica y
                muestra solución
        end note
        :Pantalla:
            - Cursos;
        note
            - Curso Aleatorio
            - Lista de Cursos
            ====
            * Todos los cursos:
                - Mínimo 1 Pregunta
        end note
        if (Selecciona)then (un Curso)
            :Pantalla:
                - Temas del Curso;
            note 
                - Tema Aleatorio
                - Lista de Temas
                ====
                * Todos los temas:
                    - Mínimo 1 Pregunta
            end note
            if (Selecciona) then (un Tema)
                :Problema de Admisión
                    del Tema seleccionado;
            else (Tema aleatorio)
                :Problema de Admisión
                    del Curso seleccionado;
            endif
        else (Curso aleatorio)
            :Problema de Admisión
                de cualquier Curso;
            note
                - De cualquier Curso
                - De cualquier Tema
            end note
        endif
        repeat :Solicita una pregunta \nal Banco de Preguntas de Da Vinci;
            :Muestra un Problema de Admisión
                del Banco de Preguntas de Da Vinci;
            note 
                - Nombre del Curso
                - Nombre del Tema
                - Enunciado
                - Alternativas
            end note
            :Selecciona una Alternativa;
            :Le da al botón:
                Enviar (Alternativa);
            :Se envía su Respuesta;
            note
                puede dejar en blanco (saltar pregunta)
            end note
            :Da Vinci evalúa su Respuesta;
            :Muestra la Solucion:
                -Enunciado
                - Alternativas
                - Resolución
                - Teoría del Tema y/o
                    Curso relacionado
                - Puntaje obtenido;
            note
                * Resalta:
                - La Alternativa enviada
                - La Alternativa correcta
            end note
            :También muestra botones de navegación;
            :Muestra un botón de Siguiente Pregunta;
            :Muestra un Problema de Admisión del Banco de Preguntas de Da Vinci;
        backward: Otra pregunta de su selección;
        repeat while (botón de Siguiente Pregunta)
    end split
backward :Selecciona otras opciones;
repeat while (botón al Home)
stop














|Backoffice|
start
:Login;
:Autenticación;
:Completar datos donde va ir la pregunta;
note
    - Área
    - Temporada (año)
    - Examen de Admisión
end note
:Ingresa pregunta;
:Agrega alternativas;
:Muesta confirmación "Pregunta ingresada";
stop

@enduml