services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api-django/dockerfiles/Dockerfile.develop
    ports:
      - 8000:8000
      - 8050:8050
      - 8500:8500
    volumes:
      - .:/daVinci
      - /daVinci/app-flutter
      - /daVinci/app-swift
    env_file:
      - api-django/.env_develop
    networks:
      - network
    healthcheck:
      test: curl --fail http://api:8000/api/v1/health_check/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  network:
    driver: bridge
