# Generated by Django 4.2.3 on 2023-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examendeadmision",
            name="cantidad_de_preguntas",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddConstraint(
            model_name="pregunta",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lectura__isnull", False), ("tema__isnull", False), _connector="OR"
                ),
                name="check_pregunta_have_tema_or_lectura",
                violation_error_message="Cada pregunta debe tener un tema o pertenecer a una lectura",
            ),
        ),
    ]
