# Generated by Django 4.2.3 on 2023-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_alternativa_solucion_alternativa_correcta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solucion",
            old_name="texto",
            new_name="resolucion",
        ),
        migrations.AddField(
            model_name="solucion",
            name="teoria",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
