# Generated by Django 4.2.3 on 2023-08-03 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_texto_solucion_resolucion_solucion_teoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pregunta",
            old_name="examen_de_admision",
            new_name="examenes_de_admision",
        ),
    ]
