# Generated by Django 4.2.3 on 2023-08-04 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_alternativa_pregunta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solucion",
            name="nombre",
        ),
    ]
