# Generated by Django 4.2.3 on 2023-08-04 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_respuesta_alternativa_valor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pregunta",
            old_name="cantidad_alternativas",
            new_name="cantidad_de_alternativas",
        ),
    ]
