# Generated by Django 4.2.3 on 2023-08-04 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_cantidad_alternativas_pregunta_cantidad_de_alternativas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lectura",
            old_name="nombre",
            new_name="titulo",
        ),
    ]
