# Generated by Django 4.2.4 on 2023-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_año_procesodeadmision_temporada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="enunciado",
            field=models.CharField(max_length=150),
        ),
    ]
