# Generated by Django 4.2.9 on 2024-01-31 07:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_pregunta_enunciado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tema",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterModelManagers(
            name="tema",
            managers=[
                ("to_ui_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
