# Generated by Django 4.2.9 on 2024-02-13 16:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_curso_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tema",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="nombre",
            ),
        ),
    ]
