version: '3.8'

services:
    api:
        container_name: api
        build:
            context: ../../.
            dockerfile: api/dockerfiles/Dockerfile.develop
        ports:
            - 8000:8000
            - 8050:8050
        volumes:
            - "$PWD:/daVinci"
        env_file:
            - ../.env
        networks:
            - net

networks:
    net:
