@startuml Pregunta Aleatoria
title Pregunta Aleatoria


start
:Abre la App;

!include screens/e00_home.puml

:Selecciona:
{{
    salt
    {+
    [ ¡Sorpréndeme! ]
    }
}}
;


!include screens/e01_pregunta_aleatoria.puml

stop



@enduml

