@startuml Da Vinci
!theme vibrant

title Da Vinci

actor Usuario
boundary App
queue Backend
database DB


Usuario -> App: Abre la App
Usuario <-- App: Muestra lista de opciones: \n- Pregunta Individual \n- Grupo de Preguntas \n- Exámenes pasados
Usuario -> App: Selecciona "Pregunta Individual"
Usuario <-- App: Muestra lista de opciones: \n- Pregunta Aleatoria \n- Elegir Curso

group#Gold  #LimeGreen Pregunta Individual
    group#SkyBlue #LightBlue Mostrar Pregunta
        group#OliveDrab #LightGray Aleatoria
            Usuario -> App: Selecciona "Pregunta Aleatoria"
            activate App
                App -> Backend: **GET /api/v1/pregunta_aleatoria/**
                activate Backend
                    Backend -> DB: Filtrar por: \n- Preguntas válidas (completas)
                    Backend <-- DB: Objeto Pregunta
                    App <-- Backend: Response: \n- Nombre del Curso \n- Nombre del Tema \n- Enunciado \n- Alternativas
                deactivate Backend
                Usuario <-- App: Muestra PEA
            deactivate App
        end

        group#AliceBlue #LightPink Elegir Curso
            Usuario -> App: Selecciona "Selecionar Curso"
            activate App
                App -> Backend: **GET /api/v1/curso/**
                activate Backend
                    Backend -> DB: Query: \n- Cursos válidos (mínimo 1 pregunta)
                    Backend <-- DB: Lista de Cursos
                    App <-- Backend: Response: \n- Lista de objetos:\n\t- id \n\t- Nombre del Curso 
                deactivate Backend
                Usuario <-- App: Muestra lista de Cursos
            deactivate App
            Usuario -> App: Selecciona un Curso
            activate App
                App -> Backend: **GET /api/v1/pregunta_individual/?curso_id=curso_id**
                activate Backend
                    Backend -> DB: Filtrar por: \n- Preguntas válidas (completas)\n- Curso seleccionado
                    Backend <-- DB: Objeto Pregunta
                    App <-- Backend: Response: \n- Nombre del Curso \n- Nombre del Tema \n- Enunciado \n- Alternativas
                deactivate Backend
                Usuario <-- App: Muestra PEA
            deactivate App
        end
    end

    group#GreenYellow #LightYellow Resolver
        Usuario -> App: Envía su Respuesta: \n- Selecciona una alternativa
        activate App
            App -> Backend: **POST /api/v1/resolver_pregunta_individual/** \n-ID de la Alternativa seleccionada
            activate Backend
                Backend -> DB: Filtrar por: \n- ID de Alternativa
                Backend <-- DB: Objeto Alternativa
                App <-- Backend: Response: \n- Solución \n- Alternativa enviada \n- Puntaje obtenido
            deactivate Backend
            Usuario <-- App: Muestra: \n- La PEA \n- La solución \n- Teoría del Tema \n- Puntaje obtenido \n- Resalta: \n\t- La alternativa enviada \n\t- La alternativa correcta \n\nTambién los botones de navegación: \n- Siguiente Pregunta:\n\t- Aleatoria\n\t- Por Curso \n- Home
        deactivate App
    end
end
@enduml