# Generated by Django 4.2.19 on 2025-02-16 12:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("letra", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Área",
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="nombre",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ExamenDeAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_correcta", models.FloatField()),
                ("puntaje_incorrecta", models.FloatField()),
                ("puntaje_en_blanco", models.FloatField(default=0)),
                ("duracion", models.DurationField()),
                (
                    "cantidad_de_preguntas",
                    models.PositiveSmallIntegerField(default=100),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen de Admisión",
                "verbose_name_plural": "Exámenes de admisión",
            },
        ),
        migrations.CreateModel(
            name="Lectura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("texto", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                (
                    "cantidad_de_alternativas",
                    models.SmallIntegerField(default=5),
                ),
                (
                    "examenes_de_admision",
                    models.ManyToManyField(to="core.examendeadmision"),
                ),
                (
                    "lectura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.lectura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Universidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("abreviatura", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Universidades",
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="nombre",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.curso",
                    ),
                ),
            ],
            options={
                "ordering": ["curso", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Solucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teoria", models.TextField()),
                ("resolucion", models.TextField()),
                (
                    "alternativa_correcta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.alternativa",
                    ),
                ),
                (
                    "pregunta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solución",
                "verbose_name_plural": "Soluciones",
            },
        ),
        migrations.CreateModel(
            name="ProcesoDeAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temporada", models.CharField(max_length=50)),
                ("proceso", models.CharField(max_length=50)),
                (
                    "universidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.universidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proceso de Admisión",
                "verbose_name_plural": "Procesos de Admisión",
            },
        ),
        migrations.CreateModel(
            name="PreguntasPorCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveSmallIntegerField()),
                ("area", models.ManyToManyField(to="core.area")),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preguntas por curso",
                "verbose_name_plural": "Preguntas por curso",
            },
        ),
        migrations.AddField(
            model_name="pregunta",
            name="tema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tema",
            ),
        ),
        migrations.AddField(
            model_name="lectura",
            name="tema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tema"
            ),
        ),
        migrations.AddField(
            model_name="examendeadmision",
            name="proceso_de_admision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.procesodeadmision",
            ),
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("vacantes_admision", models.PositiveSmallIntegerField()),
                ("vacantes_pre", models.PositiveSmallIntegerField()),
                ("codigo", models.CharField(max_length=50)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.area",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="universidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.universidad",
            ),
        ),
        migrations.AddField(
            model_name="alternativa",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.pregunta"
            ),
        ),
        migrations.AddConstraint(
            model_name="pregunta",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("lectura__isnull", False),
                    ("tema__isnull", False),
                    _connector="OR",
                ),
                name="check_pregunta_have_tema_or_lectura",
                violation_error_message="Cada pregunta debe tener un tema o pertenecer a una lectura",
            ),
        ),
    ]
