# Generated by Django 4.2.3 on 2023-08-03 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_examendeadmision_cantidad_de_preguntas_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solucion",
            old_name="alternativa",
            new_name="alternativa_correcta",
        ),
    ]
