# Generated by Django 4.2.8 on 2023-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_curso_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregunta",
            name="enunciado",
            field=models.TextField(),
        ),
    ]
