# Generated by Django 4.2.9 on 2024-01-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_tema_options_alter_tema_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="tema",
            managers=[],
        ),
    ]
