# Generated by Django 4.2.9 on 2024-02-06 02:57

from django.db import migrations, models
import django.db.models.functions.text
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_tema_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="curso",
            options={
                "ordering": [django.db.models.functions.text.Upper("nombre")]
            },
        ),
        migrations.AlterModelOptions(
            name="tema",
            options={
                "ordering": [
                    "curso",
                    django.db.models.functions.text.Upper("nombre"),
                ]
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="nombre",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
