# Generated by Django 4.2.9 on 2024-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_tema_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tema",
            options={"ordering": ["curso", "slug"]},
        ),
    ]
